# Generated by Django 6.1 on 2026-08-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=150)),
                ('skills', models.TextField()),
                ('career_interest', models.CharField(max_length=100)),
            ],
        ),
    ]
