# Generated by Django 6.1 on 2026-08-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skillassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessment',
            name='selected_skills',
            field=models.TextField(default=''),
        ),
    ]
