# Generated by Django 6.1 on 2026-08-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skillassessment_selected_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillassessment',
            name='selected_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
