# Generated by Django 6.1 on 2026-08-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_skillassessment_selected_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coding_practice', models.IntegerField(default=0)),
                ('aptitude', models.IntegerField(default=0)),
                ('cs_fundamentals', models.IntegerField(default=0)),
                ('sql_dbms', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('resume', models.IntegerField(default=0)),
                ('github_portfolio', models.IntegerField(default=0)),
                ('interview_preparation', models.IntegerField(default=0)),
                ('readiness_score', models.FloatField(default=0)),
                ('readiness_status', models.CharField(default='Beginner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile')),
            ],
        ),
    ]
