# Generated by Django 6.1 on 2026-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobreadiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillassessment',
            name='dsa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='html_css',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='java',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='python',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='selected_skills',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='sql',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
