# Generated by Django 6.1 on 2026-08-29 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_skillassessment_dsa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='aptitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='coding_practice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='cs_fundamentals',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='github_portfolio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='interview_preparation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='projects',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='readiness_status',
            field=models.CharField(default='Not Assessed', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='resume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='sql_dbms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreadiness',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_readiness', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='selected_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to='core.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='career_interest',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
