# Generated by Django 6.1 on 2026-08-29 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_skillassessment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
        ),
    ]