# Generated by Django 6.1 on 2026-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_portfolio',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
